server:
  port: 8090

#Admin configuration
info:
  name: easyms-sample-ms
  description: easyms-sample-ms
  version: 1.0.0-SNAPSHOT
  stage: local

spring:
  application:
    id: easyms-sample-ms
    name: easyms-sample-ms
  boot:
    admin:
      client:
        url: ${boot.admin.client.url}
        username: ${boot.admin.client.username}
        password: ${boot.admin.client.password}

swagger:
  paths: /api.*
  api.info:
    title: easyms-sample-ms
    description: Sample ms using easyms-rest-starter Documentation
    contact: Sample ms using easyms-rest-starter
    version: 1.0.0-SNAPSHOT
    license: license
    licenseUrl: http://easyms.fr/LICENSE-0.0.1.html

easyms:
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfig
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512

management.endpoints.web.exposure.include: "*"

