spring:
  cloud:
    stream:
      bindings:
        dummyQueueChannel:
          group: dummy.channel.group
      rabbit:
        bindings:
          dummyQueueChannel:
            consumer:
              bindingRoutingKey: dummy.channel.queue